theme: minima
title: "ChosunOne's Blog"
author: "ChosunOne"
description: "Collection of ChosunOne's thoughts"
markdown: GFM
timezone: Asia/Seoul
url: https://chosunone.github.io
plugins:
  - jekyll-sitemap
